#!/bin/bash
rm /etc/apt/sources.list.d/sileo.list
rm /etc/apt/sources.list.d/sileo.sources
mkdir /etc/apt/sillyo/
touch /etc/apt/sillyo/sileo.sources

if ! [ -s /etc/apt/sillyo/sileo.sources ]; then
	echo -e "" > /etc/apt/sillyo/sileo.sources
fi

if ! grep -Fxq "URIs: https://repounclutter.coolstar.org/" /etc/apt/sillyo/sileo.sources ;
then
	echo "Installed BigBoss+ Repo"
	sed -i '1s;^;Types: deb\nURIs: https://repounclutter.coolstar.org/\nSuites: ./\nComponents:\n\n;' /etc/apt/sillyo/sileo.sources
fi

if ! grep -Fxq "URIs: https://repo.chariz.io/" /etc/apt/sillyo/sileo.sources ;
then
	echo "Installed Chariz Repo"
	sed -i '1s;^;Types: deb\nURIs: https://repo.chariz.io/\nSuites: ./\nComponents:\n\n;' /etc/apt/sillyo/sileo.sources
fi

if ! grep -Fxq "URIs: https://repo.dynastic.co/" /etc/apt/sillyo/sileo.sources ;
then
	echo "Installed Dynastic Repo"
	sed -i '1s;^;Types: deb\nURIs: https://repo.dynastic.co/\nSuites: ./\nComponents:\n\n;' /etc/apt/sillyo/sileo.sources
fi

if ! grep -Fxq "URIs: https://apt.procurs.us/pool/main/iphoneos-arm64/1600/" /etc/apt/sillyo/sileo.sources ;
then
	echo "Installed procursus repo..."
	sed -i '1s;^;Types: deb\nURIs: https://apt.procurs.us/pool/main/iphoneos-arm64/1600/: ./\nComponents:\n\n;' /etc/apt/sillyo/sileo.sources
	echo "if error then change procursus repo to https://apt.procurs.us/pool/main/iphoneos-arm64/1500/ or https://apt.procurs.us/pool/main/iphoneos-arm64/1700/
fi

function finish() {
        f="${1}"

        # No control fd: bail out
        [[ -z "${f}" || -z "${SILEO}" ]] && return
        sileo=(${SILEO})

        # Sileo control fd version < 1: bail out
        [[ ${sileo[1]} -ge 1 ]] || return

        echo "finish:${f}" >&${sileo[0]}
}

finish uicache
exit 0
